# Generated by Django 5.2.3 on 2025-06-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_task_tarefas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='completed',
            new_name='concluida',
        ),
        migrations.RenameField(
            model_name='tarefas',
            old_name='title',
            new_name='titulo',
        ),
    ]
